/*
 * Copyright IBM Corp. 2026, 2026
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms provided by IBM in the LICENSE file that accompanied
 * this code, including the "Classpath" Exception described therein.
 */

package com.ibm.crypto.plus.provider;

class DefaultSemeruDefaultsAttrs {
    static String defaultSemeruDefaultsAttrs = "Service.AlgorithmParameters.PBEWithHmacSHA1AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA1AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA1AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA1AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA224AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA224AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA224AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA224AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA256AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA256AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA256AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA256AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA384AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA384AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA384AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA384AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA512AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA512AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA512AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA512AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndDESede = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC2_40 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC2_128 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC4_40 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC4_128 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "# =======================================================================\n"
        + " # Algorithm parameter generation engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Cipher engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.Cipher.PBEWithHmacSHA1AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA1AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA1AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA1AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA224AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA224AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA224AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA224AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA256AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA256AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA256AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA256AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA384AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA384AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA384AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA384AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA512AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA512AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA512AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA512AndAES_256\n"
        + "Service.Cipher.PBEWithSHA1AndDESede = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndDESede\n"
        + "Service.Cipher.PBEWithSHA1AndRC2_40 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC2_40\n"
        + "Service.Cipher.PBEWithSHA1AndRC2_128 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC2_128\n"
        + "Service.Cipher.PBEWithSHA1AndRC4_40 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC4_40\n"
        + "Service.Cipher.PBEWithSHA1AndRC4_128 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC4_128\n"
        + "# =======================================================================\n"
        + " # Key agreement\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Key factories\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC key factories\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Key Generator engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Keypair Generator engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC key pair generators\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Message authentication engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + "# HKDF Algorithms use key generator spis - OIDs are not finalized\n"
        + "# Oracle does not go through provider. Directly calls HKDF. Not supported till\n"
        + "# Next GSkit Crypto FIPS certification.\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # MessageDigest engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC key encapsulation mechanisms\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Secret key factories\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA1AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA1AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA1AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA1AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA224AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA224AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA224AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA224AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA256AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA256AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA256AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA256AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA384AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA384AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA384AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA384AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA512AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA512AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA512AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA512AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndDESede = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndDESede\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC2_40 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC2_40\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC2_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC2_128\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC4_40 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC4_40\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC4_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC4_128\n"
        + "# =======================================================================\n"
        + " # SecureRandom\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Signature engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC signatures\n"
        + " # =======================================================================\n"
        + " #\n";
        
    public DefaultSemeruDefaultsAttrs() {
    }

    public static String getConfigString() {
        return defaultSemeruDefaultsAttrs;
    }
}
