/*
 * Copyright IBM Corp. 2026
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms provided by IBM in the LICENSE file that accompanied
 * this code, including the "Classpath" Exception described therein.
 */

package com.ibm.crypto.plus.provider;

class DefaultInternalProviderAttrs {
    static final boolean allowLegacyHKDF = Boolean.getBoolean("openjceplus.allowLegacyHKDF");
    static String defaultInternalProvAttrs = "Service.AlgorithmParameters.AES = com.ibm.crypto.plus.provider.AESParameters\n"

        + "Service.AlgorithmParameters.PBEWithHmacSHA1AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA1AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA1AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA1AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA224AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA224AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA224AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA224AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA256AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA256AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA256AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA256AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA384AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA384AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA384AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA384AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA512AndAES_128 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA512AndAES_128\n"
        + "Service.AlgorithmParameters.PBEWithHmacSHA512AndAES_256 = com.ibm.crypto.plus.provider.PBES2Parameters$HmacSHA512AndAES_256\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndDESede = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC2_40 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC2_128 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC4_40 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "Service.AlgorithmParameters.PBEWithSHA1AndRC4_128 = com.ibm.crypto.plus.provider.PBEParameters\n"
        + "# =======================================================================\n"
        + " # Algorithm parameter generation engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Cipher engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.Cipher.PBEWithHmacSHA1AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA1AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA1AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA1AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA224AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA224AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA224AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA224AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA256AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA256AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA256AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA256AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA384AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA384AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA384AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA384AndAES_256\n"
        + "Service.Cipher.PBEWithHmacSHA512AndAES_128 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA512AndAES_128\n"
        + "Service.Cipher.PBEWithHmacSHA512AndAES_256 = com.ibm.crypto.plus.provider.PBES2Core$HmacSHA512AndAES_256\n"
        + "Service.Cipher.PBEWithSHA1AndDESede = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndDESede\n"
        + "Service.Cipher.PBEWithSHA1AndRC2_40 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC2_40\n"
        + "Service.Cipher.PBEWithSHA1AndRC2_128 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC2_128\n"
        + "Service.Cipher.PBEWithSHA1AndRC4_40 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC4_40\n"
        + "Service.Cipher.PBEWithSHA1AndRC4_128 = com.ibm.crypto.plus.provider.PBES1Core$PBEWithSHA1AndRC4_128\n"
        + "# =======================================================================\n"
        + " # Key agreement\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Key factories\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC key factories\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.KeyFactory.ML-KEM = com.ibm.crypto.plus.provider.PQCKeyFactory$MLKEM\n"
        + "KeyFactory.ML-KEM-512.alias.add = ML_KEM_512, MLKEM512, OID.2.16.840.1.101.3.4.4.1, 2.16.840.1.101.3.4.4.1\n"
        + "Service.KeyFactory.ML-KEM-512 = com.ibm.crypto.plus.provider.PQCKeyFactory$MLKEM512\n"
        + "KeyFactory.ML-KEM-768.alias.add = ML_KEM_768, MLKEM768, OID.2.16.840.1.101.3.4.4.2, 2.16.840.1.101.3.4.4.2\n"
        + "Service.KeyFactory.ML-KEM-768 = com.ibm.crypto.plus.provider.PQCKeyFactory$MLKEM768\n"
        + "KeyFactory.ML-KEM-1024.alias.add = ML_KEM_1024, MLKEM1024, OID.2.16.840.1.101.3.4.4.3, 2.16.840.1.101.3.4.4.3\n"
        + "Service.KeyFactory.ML-KEM-1024 = com.ibm.crypto.plus.provider.PQCKeyFactory$MLKEM1024\n"
        + "KeyFactory.ML-DSA-44.alias.add = ML_DSA_44, MLDSA44, OID.2.16.840.1.101.3.4.3.17, 2.16.840.1.101.3.4.3.17\n"
        + "Service.KeyFactory.ML-DSA-44 = com.ibm.crypto.plus.provider.PQCKeyFactory$MLDSA44\n"
        + "KeyFactory.ML-DSA-65.alias.add = ML-DSA, ML_DSA_65, MLDSA65, OID.2.16.840.1.101.3.4.3.18, 2.16.840.1.101.3.4.3.18\n"
        + "Service.KeyFactory.ML-DSA-65 = com.ibm.crypto.plus.provider.PQCKeyFactory$MLDSA65\n"
        + "KeyFactory.ML-DSA-87.alias.add = ML_DSA_87, MLDSA87, OID.2.16.840.1.101.3.4.3.19, 2.16.840.1.101.3.4.3.19\n"
        + "Service.KeyFactory.ML-DSA-87 = com.ibm.crypto.plus.provider.PQCKeyFactory$MLDSA87\n"
        + "# =======================================================================\n"
        + " # Key Generator engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # Keypair Generator engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC key pair generators\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.KeyPairGenerator.ML-KEM = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLKEM\n"
        + "Service.KeyPairGenerator.ML-DSA = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLDSA\n"
        + "KeyPairGenerator.ML-KEM-512.alias.add = ML_KEM_512, MLKEM512, OID.2.16.840.1.101.3.4.4.1, 2.16.840.1.101.3.4.4.1\n"
        + "Service.KeyPairGenerator.ML-KEM-512 = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLKEM512\n"
        + "KeyPairGenerator.ML-KEM-768.alias.add = ML_KEM_768, MLKEM768, OID.2.16.840.1.101.3.4.4.2, 2.16.840.1.101.3.4.4.2\n"
        + "Service.KeyPairGenerator.ML-KEM-768 = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLKEM768\n"
        + "KeyPairGenerator.ML-KEM-1024.alias.add = ML_KEM_1024, MLKEM1024, OID.2.16.840.1.101.3.4.4.3, 2.16.840.1.101.3.4.4.3\n"
        + "Service.KeyPairGenerator.ML-KEM-1024 = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLKEM1024\n"
        + "KeyPairGenerator.ML-DSA-44.alias.add = ML_DSA_44, MLDSA44, OID.2.16.840.1.101.3.4.3.17, 2.16.840.1.101.3.4.3.17\n"
        + "Service.KeyPairGenerator.ML-DSA-44 = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLDSA44\n"
        + "KeyPairGenerator.ML-DSA-65.alias.add = ML_DSA_65, MLDSA65, OID.2.16.840.1.101.3.4.3.18, 2.16.840.1.101.3.4.3.18\n"
        + "Service.KeyPairGenerator.ML-DSA-65 = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLDSA65\n"
        + "KeyPairGenerator.ML-DSA-87.alias.add = ML_DSA_87, MLDSA87, OID.2.16.840.1.101.3.4.3.19, 2.16.840.1.101.3.4.3.19\n"
        + "Service.KeyPairGenerator.ML-DSA-87 = com.ibm.crypto.plus.provider.PQCKeyPairGenerator$MLDSA87\n"
        + "# =======================================================================\n"
        + " # Message authentication engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + "# HKDF Algorithms use key generator spis - OIDs are not finalized\n"
        + "# Oracle does not go through provider. Directly calls HKDF. Not supported till\n"
        + "# Next GSkit Crypto FIPS certification.\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # MessageDigest engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC key encapsulation mechanisms\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.KEM.ML-KEM = com.ibm.crypto.plus.provider.MLKEMImpl$MLKEM\n"
        + "KEM.ML-KEM-512.alias.add = ML_KEM_512, MLKEM512, OID.2.16.840.1.101.3.4.4.1, 2.16.840.1.101.3.4.4.1\n"
        + "Service.KEM.ML-KEM-512 = com.ibm.crypto.plus.provider.MLKEMImpl$MLKEM512\n"
        + "KEM.ML-KEM-768.alias.add = ML_KEM_768, MLKEM768, OID.2.16.840.1.101.3.4.4.2, 2.16.840.1.101.3.4.4.2\n"
        + "Service.KEM.ML-KEM-768 = com.ibm.crypto.plus.provider.MLKEMImpl$MLKEM768\n"

        + "KEM.ML-KEM-1024.alias.add = ML_KEM_1024, MLKEM1024, OID.2.16.840.1.101.3.4.4.3, 2.16.840.1.101.3.4.4.3\n"
        + "Service.KEM.ML-KEM-1024 = com.ibm.crypto.plus.provider.MLKEMImpl$MLKEM1024\n"
        + "# =======================================================================\n"
        + " # Secret key factories\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA1AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA1AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA1AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA1AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA224AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA224AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA224AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA224AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA256AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA256AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA256AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA256AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA384AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA384AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA384AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA384AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA512AndAES_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA512AndAES_128\n"
        + "Service.SecretKeyFactory.PBEWithHmacSHA512AndAES_256 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithHmacSHA512AndAES_256\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndDESede = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndDESede\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC2_40 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC2_40\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC2_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC2_128\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC4_40 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC4_40\n"
        + "Service.SecretKeyFactory.PBEWithSHA1AndRC4_128 = com.ibm.crypto.plus.provider.PBEKeyFactory$PBEWithSHA1AndRC4_128\n"
        + "# =======================================================================\n"
        + " # SecureRandom\n"
        + " # =======================================================================\n"
        + " #\n"
        + "SecureRandom.SHA256DRBG.alias.add = HASHDRBG, SHA2DRBG\n"
        + "SecureRandom.SHA256DRBG.attr.add.ThreadSafe = true\n"
        + "Service.SecureRandom.SHA256DRBG = com.ibm.crypto.plus.provider.HASHDRBG$SHA256DRBG\n"
        + "SecureRandom.SHA512DRBG.alias.add = SHA5DRBG\n"
        + "SecureRandom.SHA512DRBG.attr.add.ThreadSafe = true\n"
        + "Service.SecureRandom.SHA512DRBG = com.ibm.crypto.plus.provider.HASHDRBG$SHA512DRBG\n"
        + "# =======================================================================\n"
        + " # Signature engines\n"
        + " # =======================================================================\n"
        + " #\n"
        + "# =======================================================================\n"
        + " # PQC signatures\n"
        + " # =======================================================================\n"
        + " #\n"
        + "Signature.ML-DSA-44.alias.add = ML_DSA_44, MLDSA44, OID.2.16.840.1.101.3.4.3.17, 2.16.840.1.101.3.4.3.17\n"
        + "Service.Signature.ML-DSA-44 = com.ibm.crypto.plus.provider.PQCSignatureImpl$MLDSA44\n"
        + "Signature.ML-DSA-65.alias.add = ML-DSA, ML_DSA_65, MLDSA65, OID.2.16.840.1.101.3.4.3.18, 2.16.840.1.101.3.4.3.18\n"
        + "Service.Signature.ML-DSA-65 = com.ibm.crypto.plus.provider.PQCSignatureImpl$MLDSA65\n"
        + "Signature.ML-DSA-87.alias.add = ML_DSA_87, MLDSA87, OID.2.16.840.1.101.3.4.3.19, 2.16.840.1.101.3.4.3.19\n"
        + "Service.Signature.ML-DSA-87 = com.ibm.crypto.plus.provider.PQCSignatureImpl$MLDSA87\n";
        
    public DefaultInternalProviderAttrs() {
    }

    public static String getConfigString() {
        String result = defaultInternalProvAttrs;
        return result;
    }
}
