###############################################################################
#
# Copyright IBM Corp. 2026, 2026
#
# This code is free software; you can redistribute it and/or modify it
# under the terms provided by IBM in the LICENSE file that accompanied
# this code, including the "Classpath" Exception described therein.
###############################################################################

name: GitHub Actions OpenJCEPlus Dependency Check
run-name: ${{ github.actor }} is running scheduled dependency check 🚀
on:
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 10 * * 6,0' # 10:00 UTC = 6:00 AM EDT, Saturday and Sunday
  workflow_dispatch:
jobs:
  Dependency-Check-OpenJCEPlus:
    name: Scheduled OpenJCEPlus Dependency Check
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      contents: read
    strategy:
        matrix:
          os: [ubuntu-22.04]
          include:
            - os: ubuntu-22.04
              gskit_dir: amd64
              gskit_lib_name: libjgsk8iccs_64.so
              target_lib_bin_dir: jgskit-xa-64
              github_actions_runner_root: /
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to run dependency check on the runner."
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}
      - name: Setup Temurin JDK
        uses: actions/setup-java@v4
        with:
          java-version: '26-ea'
          distribution: 'temurin'
          architecture: 'x64'
      - name: Run dependency-check check
        run: > 
          mvn
          --batch-mode
          dependency-check:check
      - name: Upload dependency-check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
      - name: Add dependency-check summary
        if: always()
        run: |
          echo "The Dependency Check Report was uploaded as artifact: \`dependency-check-report\`." >> $GITHUB_STEP_SUMMARY
      - run: echo "🍏 This job's status is ${{ job.status }}."
